- name: Play for cachyos
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      ansible.builtin.package:
        update_cache: true
      changed_when: false

  tasks:
    - name: Fix Kevin Shell
      ansible.builtin.include_tasks: tasks/fix_kevin_shell.yml
    - name: Install pacman packages
      ansible.builtin.include_tasks: tasks/packages.yml
    - name: Install AUR packages
      ansible.builtin.include_tasks: install_aur_package.yml
