- name: Play for cachyos
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      ansible.builtin.package:
        update_cache: true
      changed_when: false

  handlers:
    - name: restart_systemd_resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted

  tasks:
    - name: Loop through various tasks
      ansible.builtin.include_tasks: "tasks/{{ item }}"
      loop:
        - fix_kevin_shell.yml
        - packages.yml
        - install_aur_package.yml
        - fix_mdns.yml
        - configure_cctv.yml
        - make_vim_default.yml
        - copy_ssh_stuff.yml
