- name: Copy ssh files
  ansible.builtin.copy:
    src: "files/{{ src_file }}"
    dest: "~kevin/.ssh/"
    mode: "0600"
    owner: kevin
    group: kevin
  loop:
    - authorized_keys
    - id_ed25519
    - id_ed25519.pub
  loop_control:
    loop_var: src_file
