- name: Create aur_builder user
  ansible.builtin.user:
    name: aur_builder
    create_home: true

- name: Allow aur_builder to sudo pacman
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
    state: present
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: /usr/sbin/visudo -cf %s
    mode: "0440"
