- name: Create aur_builder user
  user: name=aur_builder create_home=yes

- name: Allow aur_builder to sudo pacman
  lineinfile:
    path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
    state: present
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: /usr/sbin/visudo -cf %s
