- name: Install AUR package
  kewlfft.aur.aur:
    name: 
      - visual-studio-code-bin
      - cctv-viewer-git
      - thonny
      - nordvpn-bin
      - easyeda-pro-bin
      - brother-hll2300d
    state: latest
  become: true
  became_user: aur_builder
