- name: Install common packages
  ansible.builtin.package:
    name:
      - screen
      - uv
      - ansible
      - ansible-lint
      - telegram-desktop
      - avahi
      - vivaldi
      - tailscale
    state: latest
