- name: Install common packages
  ansible.builtin.package:
    name:
      - screen
      - uv
      - ansible
      - ansible-lint
      - telegram-desktop
      - avahi
      - vivaldi
      - tailscale
      - plasma-x11-session
      - kwin-x11
      - xorg-server
    state: present
