- name: Copy GPU workarounds
  ansible.builtin.copy:
    src: "files/{{ src_app_file }}"
    dest: "~kevin/.local/share/applications/"
    mode: "0600"
    owner: kevin
    group: kevin
  loop:
    - cctv-viewer.desktop
    - code.desktop
    - vivaldi-stable.desktop
  loop_control:
    loop_var: src_app_file
  #when: ansible_facts['ansible_board_version'] == "MacBookAir4,2"

